# Generated by Django 5.2.17 on 2026-08-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_offre', models.CharField(choices=[('carnet', 'Carnet de séances'), ('famille', 'Offre famille'), ('personnalisee', 'Offre personnalisée')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nombre_seances', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
