# Generated by Django 5.2.17 on 2026-09-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='duree_validite_mois',
            field=models.PositiveIntegerField(blank=True, help_text="Durée (en mois) dont un achat de cette offre prolonge la validité de l'ensemble du solde du membre (ou de sa famille). Vide = n'affecte pas la date d'expiration (ex : achat à l'unité).", null=True),
        ),
    ]
