# Generated by Django 5.2.17 on 2026-09-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_seed_offres_carnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='nombre_seances_offertes',
            field=models.PositiveIntegerField(default=0, help_text="Parmi le nombre de séances ci-dessus, combien sont offertes (à but d'affichage uniquement — le nombre total crédité au solde reste « Nombre de séances »)."),
        ),
    ]
