# Generated by Django 5.2.17 on 2026-08-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, help_text='Utilisé pour les notifications par SMS/WhatsApp (à venir).', max_length=20),
        ),
    ]
