# Generated by Django 5.2.17 on 2026-08-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, help_text='Utilisé pour les notifications par SMS/WhatsApp (à venir).', max_length=20, verbose_name='téléphone'),
        ),
    ]
