# Generated by Django 5.2.17 on 2026-08-15 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('tolerance_seances_negatives', models.PositiveIntegerField(default=0, help_text='Tolérance de séances négatives appliquée au pool partagé, pour tous les membres liés.')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'famille',
                'verbose_name_plural': 'familles',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='tolerance_seances_negatives',
            field=models.PositiveIntegerField(default=0, help_text="Nombre de séances que ce membre peut avoir en négatif avant blocage de l'inscription. Ignoré si le membre appartient à une famille (voir Famille.tolerance_seances_negatives).", verbose_name='tolérance de séances négatives'),
        ),
        migrations.AddField(
            model_name='user',
            name='famille',
            field=models.ForeignKey(blank=True, help_text='Si renseigné, ce membre partage le pool de séances et la tolérance négative de sa famille.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='accounts.famille'),
        ),
    ]
