# Generated by Django 5.2.17 on 2026-08-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_famille_alter_user_tolerance_seances_negatives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='date_expiration_solde',
            field=models.DateField(blank=True, help_text='Au-delà de cette date, le solde de séances du pool est considéré à zéro. Prolongée de 6 mois à chaque achat.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_expiration_solde',
            field=models.DateField(blank=True, help_text='Au-delà de cette date, le solde de séances est considéré à zéro. Prolongée de 6 mois à chaque achat. Ignorée si le membre appartient à une famille (voir Famille.date_expiration_solde).', null=True),
        ),
    ]
