# Generated by Django 5.2.17 on 2026-09-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_famille_date_expiration_solde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('gestionnaire', 'Coach'), ('membre', 'Membre')], default='membre', max_length=20),
        ),
    ]
