# Generated by Django 5.2.17 on 2026-09-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_reacquisition_joker',
            field=models.DateField(blank=True, help_text='Date à partir de laquelle un nouveau joker peut être ré-attribué (3 mois après la consommation du précédent). Effacée si un joker est attribué manuellement avant cette date.', null=True),
        ),
    ]
