# Generated by Django 5.2.17 on 2026-09-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_date_reacquisition_joker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('gestionnaire', 'Coach gestionnaire'), ('coach', 'Coach'), ('membre', 'Membre')], default='membre', max_length=20),
        ),
    ]
