# Generated by Django 5.2.17 on 2026-09-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='topic_ntfy_coach',
            field=models.CharField(blank=True, editable=False, help_text='Canal ntfy individuel, généré automatiquement pour les comptes qui animent des séances (coach, coach gestionnaire, admin). Notifie séance pleine et désinscriptions.', max_length=64, null=True, unique=True),
        ),
    ]
