# Generated by Django 5.2.17 on 2026-09-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_backfill_topic_ntfy_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepte_emails',
            field=models.BooleanField(default=True, help_text='Consentement général à recevoir des emails de notification (ouverture des inscriptions, solde bas, crédit renouvelé, etc.).', verbose_name='accepte de recevoir des emails'),
        ),
    ]
