# Generated by Django 5.2.17 on 2026-09-14 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_accepte_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coachs_suivis',
            field=models.ManyToManyField(blank=True, help_text='Coachs dont ce compte veut suivre les séances (vide = tous). Pertinent seulement pour un coach gestionnaire ou un admin — un coach simple ne suit que ses propres séances.', related_name='suivi_par', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='notifie_desinscription',
            field=models.BooleanField(default=True, help_text='Notifier ce compte (canal ntfy individuel) à chaque désinscription.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notifie_inscription',
            field=models.BooleanField(default=True, help_text='Notifier ce compte (canal ntfy individuel) à chaque inscription.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notifie_promotion_automatique',
            field=models.BooleanField(default=True, help_text="Notifier ce compte (canal ntfy individuel) lors d'une promotion automatique depuis la liste d'attente."),
        ),
        migrations.AddField(
            model_name='user',
            name='notifie_seance_complete',
            field=models.BooleanField(default=True, help_text='Notifier ce compte (canal ntfy individuel) quand une séance devient complète.'),
        ),
    ]
