# Generated by Django 5.2.17 on 2026-09-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_coachs_suivis_user_notifie_desinscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accepte_emails',
        ),
        migrations.AddField(
            model_name='user',
            name='email_ouverture_seance',
            field=models.BooleanField(default=True, help_text="Recevoir un email à l'ouverture des inscriptions à une séance. Le mot de passe oublié est envoyé quoi qu'il arrive, indépendamment de ce réglage.", verbose_name="email à l'ouverture des inscriptions"),
        ),
    ]
