# Generated by Django 5.2.17 on 2026-09-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_user_accepte_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_annulation_seance',
            field=models.BooleanField(default=True, help_text='Recevoir un email quand une séance à laquelle vous êtes inscrit(e) est annulée par le gestionnaire.', verbose_name="email en cas d'annulation d'une séance"),
        ),
    ]
