# Generated by Django 5.2.17 on 2026-09-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='cible',
            field=models.CharField(blank=True, choices=[('calendrier', 'Calendrier'), ('offres', 'Offres'), ('notifications', 'Notifications'), ('solde', 'Solde')], help_text="Bouton optionnel renvoyant vers une page de l'application.", max_length=20),
        ),
    ]
