# Generated by Django 5.2.17 on 2026-08-13 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('duree_minutes', models.PositiveIntegerField(default=60)),
                ('capacite_max_defaut', models.PositiveIntegerField()),
                ('delai_annulation_defaut_heures', models.PositiveIntegerField(default=24, help_text='Délai avant le début de la séance en dessous duquel une désinscription est considérée tardive.')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('capacite_max', models.PositiveIntegerField()),
                ('delai_annulation_heures', models.PositiveIntegerField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_animees', to=settings.AUTH_USER_MODEL)),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='scheduling.modeleseance')),
            ],
            options={
                'ordering': ['debut'],
            },
        ),
    ]
