# Generated by Django 5.2.17 on 2026-08-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='fin',
        ),
        migrations.AddField(
            model_name='seance',
            name='duree_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='seance',
            name='capacite_max',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='seance',
            name='delai_annulation_heures',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
