# Generated by Django 5.2.17 on 2026-08-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_remove_seance_fin_seance_duree_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='notification_ouverture_envoyee',
            field=models.BooleanField(default=False, help_text="Empêche de renotifier plusieurs fois l'ouverture des inscriptions pour cette séance."),
        ),
    ]
