# Generated by Django 5.2.17 on 2026-08-13 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('desinscrit', 'Désinscrit'), ('desinscrit_tardif_joker', 'Désinscrit tardivement (joker utilisé)'), ('desinscrit_tardif_sans_joker', 'Désinscrit tardivement (séance perdue)')], default='inscrit', max_length=40)),
                ('inscrit_le', models.DateTimeField(auto_now_add=True)),
                ('desinscrit_le', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(help_text="Utilisateur à l'origine de l'action (le membre lui-même ou un gestionnaire/admin agissant pour lui).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_effectuees', to=settings.AUTH_USER_MODEL)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='scheduling.seance')),
            ],
            options={
                'ordering': ['-inscrit_le'],
            },
        ),
        migrations.CreateModel(
            name='MouvementJoker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Positif pour une attribution, négatif pour une utilisation.')),
                ('motif', models.CharField(choices=[('attribution', 'Attribution par un gestionnaire'), ('utilisation', "Utilisé lors d'une désinscription tardive")], max_length=20)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(help_text="Gestionnaire/admin à l'origine de l'attribution, ou le système lors d'une utilisation automatique.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jokers_attribues', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_jokers', to='bookings.inscription')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_jokers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-horodatage'],
            },
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'inscrit')), fields=('membre', 'seance'), name='unique_inscription_active_par_membre_et_seance'),
        ),
    ]
