# Generated by Django 5.2.17 on 2026-08-19 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('scheduling', '0002_remove_seance_fin_seance_duree_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inscription',
            name='unique_inscription_active_par_membre_et_seance',
        ),
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('inscrit', 'Inscrit'), ('en_attente', "En liste d'attente"), ('desinscrit', 'Désinscrit'), ('desinscrit_tardif_joker', 'Désinscrit tardivement (joker utilisé)'), ('desinscrit_tardif_sans_joker', 'Désinscrit tardivement (séance perdue)')], default='inscrit', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['inscrit', 'en_attente'])), fields=('membre', 'seance'), name='unique_inscription_active_par_membre_et_seance'),
        ),
    ]
