# Generated by Django 5.2.17 on 2026-08-19 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_inscription_unique_inscription_active_par_membre_et_seance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='auteur',
            field=models.ForeignKey(help_text="Utilisateur à l'origine de la dernière action sur cette inscription (le membre lui-même, ou un gestionnaire/admin agissant pour lui).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_effectuees', to=settings.AUTH_USER_MODEL),
        ),
    ]
