# Generated by Django 5.2.17 on 2026-09-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_inscription_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementjoker',
            name='commentaire',
            field=models.TextField(blank=True, help_text="Motif saisi par le coach lors d'une attribution/utilisation manuelle (non renseigné pour une désinscription tardive automatique, déjà tracée via l'inscription liée)."),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('inscrit', 'Inscrit'), ('en_attente', "En liste d'attente"), ('desinscrit', 'Désinscrit'), ('desinscrit_tardif_joker', 'Désinscrit tardivement (joker utilisé)'), ('desinscrit_tardif_sans_joker', 'Désinscrit tardivement (séance perdue)'), ('non_presente', 'Non présenté(e)')], default='inscrit', max_length=40),
        ),
    ]
