# Generated by Django 5.2.17 on 2026-10-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_mouvementjoker_commentaire_alter_inscription_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('inscrit', 'Inscrit'), ('en_attente', "En liste d'attente"), ('desinscrit', 'Désinscrit'), ('desinscrit_tardif_joker', 'Désinscrit tardivement (joker utilisé)'), ('desinscrit_tardif_sans_joker', 'Désinscrit tardivement (séance perdue)'), ('non_presente', 'Non présenté(e)'), ('permute', 'Permuté(e) vers une autre séance')], default='inscrit', max_length=40),
        ),
    ]
