# Generated by Django 5.2.17 on 2026-08-13 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('nombre_seances', models.PositiveIntegerField(help_text="Nombre de séances accordées par cet achat (copié depuis l'offre au moment de l'achat).")),
                ('prix_paye', models.DecimalField(decimal_places=2, max_digits=8)),
                ('statut_paiement', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats', to='offers.offre')),
                ('saisi_par', models.ForeignKey(help_text='Gestionnaire ou admin ayant enregistré cet achat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_achat'],
            },
        ),
        migrations.CreateModel(
            name='MouvementSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Positif pour un crédit, négatif pour un débit.')),
                ('motif', models.CharField(choices=[('achat', 'Achat de carnet'), ('inscription', 'Inscription à une séance'), ('desinscription', 'Désinscription'), ('desinscription_tardive_joker', 'Désinscription tardive (joker utilisé)'), ('ajustement', 'Ajustement manuel')], max_length=40)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='purchases.achat')),
                ('auteur', models.ForeignKey(help_text="Utilisateur à l'origine de l'action (le membre lui-même ou un gestionnaire/admin).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_effectues', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_seances', to='bookings.inscription')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_seances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-horodatage'],
            },
        ),
    ]
