# Generated by Django 5.2.17 on 2026-09-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementseance',
            name='motif',
            field=models.CharField(choices=[('achat', 'Achat de carnet'), ('inscription', 'Inscription à une séance'), ('desinscription', 'Désinscription'), ('desinscription_tardive_joker', 'Désinscription tardive (joker utilisé)'), ('desinscription_tardive_sans_joker', 'Désinscription tardive (séance perdue)'), ('ajustement', 'Ajustement manuel')], max_length=40),
        ),
    ]
