# Generated by Django 5.2.17 on 2026-10-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_alter_mouvementseance_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementseance',
            name='motif',
            field=models.CharField(choices=[('achat', 'Achat de carnet'), ('inscription', 'Inscription à une séance'), ('desinscription', 'Désinscription'), ('desinscription_tardive_joker', 'Désinscription tardive (joker utilisé)'), ('desinscription_tardive_sans_joker', 'Désinscription tardive (séance perdue)'), ('non_presentation', 'Non présenté(e) (séance due)'), ('ajustement', 'Ajustement manuel'), ('annulation_seance', 'Séance annulée par le gestionnaire'), ('permutation', 'Permutation vers une autre séance')], max_length=40),
        ),
    ]
