# Generated by Django 5.2.17 on 2026-08-13 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('inscription', 'Inscription à une séance'), ('desinscription', 'Désinscription'), ('joker_utilise', 'Joker utilisé'), ('nouvelle_seance', "Ouverture d'une nouvelle séance"), ('solde_faible', 'Nombre de séances restantes faible')], max_length=30)),
                ('canal', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('membre', 'type_evenement', 'canal'), name='unique_preference_par_membre_evenement_canal')],
            },
        ),
    ]
