# Generated by Django 5.2.17 on 2026-09-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreferenceNotification',
        ),
    ]
